/// (name, parent_name, productivity_score)
pub const BUILTIN_CATEGORIES: &[(&str, Option<&str>, f64)] = &[
    // Top-level
    ("work", None, 1.0),
    ("communication", None, 0.5),
    ("reference", None, 0.5),
    ("entertainment", None, -1.0),
    ("social-media", None, -1.5),
    ("utilities", None, 0.0),
    ("uncategorized", None, 0.0),
    ("inappropriate-content", None, -2.0),
    // Work subcategories
    ("work/coding", Some("work"), 2.0),
    ("work/ai-tools", Some("work"), 2.0),
    ("work/terminal", Some("work"), 1.5),
    ("work/writing", Some("work"), 1.5),
    ("work/design", Some("work"), 1.0),
    // Communication subcategories
    ("communication/email", Some("communication"), 0.5),
    ("communication/chat", Some("communication"), 0.0),
    ("communication/video-call", Some("communication"), 0.5),
    // Entertainment subcategories
    ("entertainment/video", Some("entertainment"), -2.0),
    ("entertainment/music", Some("entertainment"), -0.5),
    ("entertainment/gaming", Some("entertainment"), -2.0),
    // Reference subcategories
    ("reference/docs", Some("reference"), 1.0),
    ("reference/search", Some("reference"), 0.5),
];

/// (category_name, field, pattern, priority)
pub const BUILTIN_RULES: &[(&str, &str, &str, i32)] = &[
    // IDEs & Editors
    ("work/coding", "app", "Code", 100),
    ("work/coding", "app", "Visual Studio Code", 100),
    ("work/coding", "app", "Cursor", 100),
    ("work/coding", "app", "IntelliJ IDEA", 100),
    ("work/coding", "app", "PyCharm", 100),
    ("work/coding", "app", "WebStorm", 100),
    ("work/coding", "app", "Xcode", 100),
    ("work/coding", "app", "Sublime Text", 100),
    ("work/coding", "app", "Neovim", 100),
    ("work/coding", "app", "Vim", 100),
    ("work/coding", "app", "Emacs", 100),
    ("work/coding", "app", "RustRover", 100),
    ("work/coding", "app", "Android Studio", 100),
    ("work/coding", "app", "Zed", 100),
    // AI coding assistants (detected via TUI process watcher)
    ("work/ai-tools", "app", "Claude Code", 110),
    ("work/ai-tools", "app", "Codex CLI", 110),
    ("work/ai-tools", "app", "Aider", 110),
    ("work/ai-tools", "app", "Cursor CLI", 110),
    // TUI editors (detected via TUI process watcher, higher priority than terminal)
    ("work/coding", "app", "Helix", 100),
    // TUI dev tools (detected via TUI process watcher)
    ("work/coding", "app", "Lazygit", 95),
    ("work/coding", "app", "Tig", 95),
    // Terminals (base — used when no TUI app detected inside)
    ("work/terminal", "app", "Terminal", 90),
    ("work/terminal", "app", "iTerm2", 90),
    ("work/terminal", "app", "Alacritty", 90),
    ("work/terminal", "app", "kitty", 90),
    ("work/terminal", "app", "Warp", 90),
    ("work/terminal", "app", "WezTerm", 90),
    ("work/terminal", "app", "Ghostty", 90),
    // Writing
    ("work/writing", "app", "Notion", 80),
    ("work/writing", "app", "Obsidian", 80),
    ("work/writing", "app", "Pages", 80),
    ("work/writing", "app", "Microsoft Word", 80),
    ("work/writing", "app", "Google Docs", 80),
    ("work/writing", "app", "Bear", 80),
    // Design
    ("work/design", "app", "Figma", 80),
    ("work/design", "app", "Sketch", 80),
    ("work/design", "app", "Adobe Photoshop", 80),
    ("work/design", "app", "Adobe Illustrator", 80),
    // Communication
    ("communication/email", "app", "Mail", 70),
    ("communication/email", "app", "Outlook", 70),
    ("communication/email", "url_domain", "mail.google.com", 70),
    ("communication/email", "url_domain", "outlook.live.com", 70),
    ("communication/chat", "app", "Slack", 70),
    ("communication/chat", "app", "Discord", 60),
    ("communication/chat", "app", "Messages", 60),
    ("communication/chat", "app", "Telegram", 60),
    ("communication/chat", "app", "WhatsApp", 60),
    ("communication/chat", "app", "Microsoft Teams", 70),
    ("communication/video-call", "app", "zoom.us", 70),
    ("communication/video-call", "app", "FaceTime", 70),
    ("communication/video-call", "app", "Google Meet", 70),
    // Entertainment
    ("entertainment/video", "url_domain", "youtube.com", 50),
    ("entertainment/video", "url_domain", "www.youtube.com", 50),
    ("entertainment/video", "url_domain", "netflix.com", 50),
    ("entertainment/video", "url_domain", "www.netflix.com", 50),
    ("entertainment/video", "url_domain", "twitch.tv", 50),
    ("entertainment/video", "url_domain", "www.twitch.tv", 50),
    ("entertainment/video", "app", "TV", 50),
    ("entertainment/video", "app", "VLC", 50),
    ("entertainment/video", "app", "IINA", 50),
    ("entertainment/music", "app", "Spotify", 50),
    ("entertainment/music", "app", "Music", 50),
    ("entertainment/music", "app", "Apple Music", 50),
    ("entertainment/gaming", "app", "Steam", 50),
    // Social Media
    ("social-media", "url_domain", "twitter.com", 60),
    ("social-media", "url_domain", "x.com", 60),
    ("social-media", "url_domain", "reddit.com", 60),
    ("social-media", "url_domain", "www.reddit.com", 60),
    ("social-media", "url_domain", "facebook.com", 60),
    ("social-media", "url_domain", "www.facebook.com", 60),
    ("social-media", "url_domain", "instagram.com", 60),
    ("social-media", "url_domain", "www.instagram.com", 60),
    ("social-media", "url_domain", "linkedin.com", 50),
    ("social-media", "url_domain", "www.linkedin.com", 50),
    // Reference
    ("reference/docs", "url_domain", "docs.rs", 80),
    ("reference/docs", "url_domain", "doc.rust-lang.org", 80),
    ("reference/docs", "url_domain", "developer.apple.com", 80),
    ("reference/docs", "url_domain", "developer.mozilla.org", 80),
    ("reference/docs", "url_domain", "docs.github.com", 80),
    ("reference/docs", "url_domain", "stackoverflow.com", 80),
    ("reference/docs", "url_domain", "github.com", 75),
    ("reference/search", "url_domain", "google.com", 60),
    ("reference/search", "url_domain", "www.google.com", 60),
    ("reference/search", "url_domain", "duckduckgo.com", 60),
    // Utilities
    ("utilities", "app", "Finder", 40),
    ("utilities", "app", "System Preferences", 40),
    ("utilities", "app", "System Settings", 40),
    ("utilities", "app", "Activity Monitor", 40),
    ("utilities", "app", "Preview", 40),
    ("utilities", "app", "Calculator", 40),
    ("utilities", "app", "1Password", 40),
    // Inappropriate / Adult content — keyword globs (high priority)
    // These match any domain containing the keyword, scaling to millions of sites
    ("inappropriate-content", "url_domain", "*porn*", 200),
    ("inappropriate-content", "url_domain", "*xvideo*", 200),
    ("inappropriate-content", "url_domain", "*xnxx*", 200),
    ("inappropriate-content", "url_domain", "*xhamster*", 200),
    ("inappropriate-content", "url_domain", "*redtube*", 200),
    ("inappropriate-content", "url_domain", "*youporn*", 200),
    ("inappropriate-content", "url_domain", "*spankbang*", 200),
    ("inappropriate-content", "url_domain", "*chaturbate*", 200),
    ("inappropriate-content", "url_domain", "*stripchat*", 200),
    ("inappropriate-content", "url_domain", "*onlyfans*", 200),
    ("inappropriate-content", "url_domain", "*cam4.*", 200),
    ("inappropriate-content", "url_domain", "*hentai*", 200),
    ("inappropriate-content", "url_domain", "*brazzers*", 200),
    ("inappropriate-content", "url_domain", "*livejasmin*", 200),
    ("inappropriate-content", "url_domain", "*xxx*", 200),
];
